### ISSUE TITLE
Shadowsocks and OSX 10.9

### ISSUE THREAD

**Issue by mrpropre** [shadowsocks/ShadowsocksX-NG#444]
Hi,

Is there a way to make it work in OSX 10.9?

Thanks a lot for this great piece of software!

**Comment by mrpropre** [comment]
I tried [that one ](https://github.com/shadowsocks/ShadowsocksX-NG/issues/35#issuecomment-243062899) but it closed itself with OSX Maverick 10.9.5:

Last login: Sat Aug  5 18:37:59 on console
localhost:~ raphael$ /Users/raphael/Downloads/ShadowsocksX-NG-R5for10.9.app/Contents/MacOS/ShadowsocksX-NG ; exit;
dyld: lazy symbol binding failed: Symbol not found: _LSSharedFileListItemCopyResolvedURL
  Referenced from: /Users/raphael/Downloads/ShadowsocksX-NG-R5for10.9.app/Contents/MacOS/ShadowsocksX-NG
  Expected in: /System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices

dyld: Symbol not found: _LSSharedFileListItemCopyResolvedURL
  Referenced from: /Users/raphael/Downloads/ShadowsocksX-NG-R5for10.9.app/Contents/MacOS/ShadowsocksX-NG
  Expected in: /System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices

Trace/BPT trap: 5
logout

[Process completed]

**Comment by yangfeicheung** [comment]
this one works for 10.9:

https://github.com/yangfeicheung/Shadowsocks-X

**Comment by qiuyuzhou** [comment]
Try the legacy version https://github.com/shadowsocks/shadowsocks-iOS/releases
